package devmaster.edu.vn.entity;
// Generated Mar 2, 2024, 12:49:06 PM by Hibernate Tools 5.6.15.Final

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private ProductId id;

	public Product() {
	}

	public Product(ProductId id) {
		this.id = id;
	}

	public ProductId getId() {
		return this.id;
	}

	public void setId(ProductId id) {
		this.id = id;
	}

}
